# The following adds the Cupertino Icons font to your application.
# Use with the CupertinoIcons class for iOS style icons.
cupertino_icons: ^1.0.2
firebase_core: ^2.15.1
firebase_auth: ^4.7.3
cloud_firestore: ^4.9.1
firebase_storage: ^11.5.6
firebase_analytics: ^10.7.2
image_picker: ^1.0.7
camera: ^0.10.5+5
path: ^1.8.3
path_provider: ^2.1.1
permission_handler: ^11.0.0
share_plus: ^7.2.1
intl: ^0.18.1
fl_chart: ^0.65.0
tflite_flutter: ^0.10.1
image: ^4.0.17
shared_preferences: ^2.2.1 