// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for the app
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCYDhg6Hvf63pbzskUjFzItWm-fgBcW1yc",
    authDomain: "plantdis-e42a4.firebaseapp.com",
    projectId: "plantdis-e42a4",
    storageBucket: "plantdis-e42a4.appspot.com",
    messagingSenderId: "748587653216",
    appId: "1:748587653216:web:d7992935d3ab9ea82b8b05",
    measurementId: "G-QNCFWRG3E8",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQHSmvy5hkg4lUNxH0-HGo7Us4PUYJO_I',
    appId: '1:748587653216:android:0ae8fc58b47b2dbe2b8b05',
    messagingSenderId: '748587653216',
    projectId: 'plantdis-e42a4',
    storageBucket: 'plantdis-e42a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQHSmvy5hkg4lUNxH0-HGo7Us4PUYJO_I',
    appId: '1:748587653216:ios:0ae8fc58b47b2dbe2b8b05',
    messagingSenderId: '748587653216',
    projectId: 'plantdis-e42a4',
    storageBucket: 'plantdis-e42a4.appspot.com',
    iosBundleId: 'com.example.flutterTestApplication1',
  );
}
