name: PlantDis Flutter CI

on:
  push:
    branches: [main]
    paths:
      - 'ui_dev/flutter_test_application_1/**'
      - '.github/workflows/flutter_ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'ui_dev/flutter_test_application_1/**'
      - '.github/workflows/flutter_ci.yml'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui_dev/flutter_test_application_1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.1'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze --no-fatal-infos

      - name: Build Android APK
        run: flutter build apk --debug
